// Package coreclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package coreclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TotalUsageSlidesOrigin.
const (
	Document       TotalUsageSlidesOrigin = "document"
	None           TotalUsageSlidesOrigin = "none"
	VideoExtracted TotalUsageSlidesOrigin = "video_extracted"
)

// Valid indicates whether the value is a known member of the TotalUsageSlidesOrigin enum.
func (e TotalUsageSlidesOrigin) Valid() bool {
	switch e {
	case Document:
		return true
	case None:
		return true
	case VideoExtracted:
		return true
	default:
		return false
	}
}

// Defines values for TotalUsageSource.
const (
	Audio TotalUsageSource = "audio"
	Video TotalUsageSource = "video"
)

// Valid indicates whether the value is a known member of the TotalUsageSource enum.
func (e TotalUsageSource) Valid() bool {
	switch e {
	case Audio:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// BodyCreateTaskApiV1TasksPost defines model for Body_create_task_api_v1_tasks_post.
type BodyCreateTaskApiV1TasksPost struct {
	Audio    *string `json:"audio,omitempty"`
	Media    *string `json:"media,omitempty"`
	NoSlides *bool   `json:"no_slides,omitempty"`
	S3Key    *string `json:"s3_key,omitempty"`
	Slides   *string `json:"slides,omitempty"`
	Video    *string `json:"video,omitempty"`
	VideoUrl *string `json:"video_url,omitempty"`
}

// BodyPutYoutubeCookiesApiV1YoutubeCookiesPut defines model for Body_put_youtube_cookies_api_v1_youtube_cookies_put.
type BodyPutYoutubeCookiesApiV1YoutubeCookiesPut struct {
	File string `json:"file"`
}

// ByModelEntry defines model for ByModelEntry.
type ByModelEntry struct {
	Calls  int `json:"calls"`
	Output int `json:"output"`
	Prompt int `json:"prompt"`
}

// CookieStatusResponse defines model for CookieStatusResponse.
type CookieStatusResponse struct {
	Exists    bool       `json:"exists"`
	Size      int        `json:"size"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	TaskId string `json:"task_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Detail string `json:"detail"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// ResultUrlResponse defines model for ResultUrlResponse.
type ResultUrlResponse struct {
	ExpiresIn int    `json:"expires_in"`
	Url       string `json:"url"`
}

// StageUsage defines model for StageUsage.
type StageUsage struct {
	ByModel  *map[string]ByModelEntry `json:"by_model,omitempty"`
	Provider string                   `json:"provider"`
	Raw      *map[string]interface{}  `json:"raw,omitempty"`
}

// TaskStatusResponse defines model for TaskStatusResponse.
type TaskStatusResponse struct {
	Error       *string `json:"error"`
	ErrorCode   *string `json:"error_code"`
	ProgressPct int     `json:"progress_pct"`
	ResultPath  *string `json:"result_path"`
	Stage       *string `json:"stage"`
	TaskId      string  `json:"task_id"`
	Usage       *Usage  `json:"usage,omitempty"`
}

// TotalUsage defines model for TotalUsage.
type TotalUsage struct {
	AudioSeconds int                    `json:"audio_seconds"`
	GeminiOutput int                    `json:"gemini_output"`
	GeminiPrompt int                    `json:"gemini_prompt"`
	SlidesOrigin TotalUsageSlidesOrigin `json:"slides_origin"`
	Source       TotalUsageSource       `json:"source"`
}

// TotalUsageSlidesOrigin defines model for TotalUsage.SlidesOrigin.
type TotalUsageSlidesOrigin string

// TotalUsageSource defines model for TotalUsage.Source.
type TotalUsageSource string

// TranscribeUsage defines model for TranscribeUsage.
type TranscribeUsage struct {
	AudioSeconds int                     `json:"audio_seconds"`
	Model        *string                 `json:"model,omitempty"`
	Provider     string                  `json:"provider"`
	Raw          *map[string]interface{} `json:"raw,omitempty"`
}

// TranscriptFailedError defines model for TranscriptFailedError.
type TranscriptFailedError struct {
	Detail *string `json:"detail,omitempty"`
	Error  string  `json:"error"`
}

// TranscriptInvalidFormatError defines model for TranscriptInvalidFormatError.
type TranscriptInvalidFormatError struct {
	Allowed []string `json:"allowed"`
	Error   string   `json:"error"`
}

// TranscriptNotFoundError defines model for TranscriptNotFoundError.
type TranscriptNotFoundError struct {
	Error string `json:"error"`
}

// UploadUrlRequest defines model for UploadUrlRequest.
type UploadUrlRequest struct {
	Filename string `json:"filename"`
}

// UploadUrlResponse defines model for UploadUrlResponse.
type UploadUrlResponse struct {
	ExpiresIn int    `json:"expires_in"`
	Key       string `json:"key"`
	Url       string `json:"url"`
}

// Usage defines model for Usage.
type Usage struct {
	Structurize *StageUsage      `json:"structurize,omitempty"`
	Total       *TotalUsage      `json:"total,omitempty"`
	Transcribe  *TranscribeUsage `json:"transcribe,omitempty"`
	VideoSlides *StageUsage      `json:"video_slides,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// GetTaskResultUrlApiV1TasksTaskIdResultUrlGetParams defines parameters for GetTaskResultUrlApiV1TasksTaskIdResultUrlGet.
type GetTaskResultUrlApiV1TasksTaskIdResultUrlGetParams struct {
	Filename *string `form:"filename,omitempty" json:"filename,omitempty"`
}

// GetTaskTranscriptApiV1TasksTaskIdTranscriptGetParams defines parameters for GetTaskTranscriptApiV1TasksTaskIdTranscriptGet.
type GetTaskTranscriptApiV1TasksTaskIdTranscriptGetParams struct {
	Format *string `form:"format,omitempty" json:"format,omitempty"`
}

// CreateTaskApiV1TasksPostMultipartRequestBody defines body for CreateTaskApiV1TasksPost for multipart/form-data ContentType.
type CreateTaskApiV1TasksPostMultipartRequestBody = BodyCreateTaskApiV1TasksPost

// CreateUploadUrlApiV1UploadsPostJSONRequestBody defines body for CreateUploadUrlApiV1UploadsPost for application/json ContentType.
type CreateUploadUrlApiV1UploadsPostJSONRequestBody = UploadUrlRequest

// PutYoutubeCookiesApiV1YoutubeCookiesPutMultipartRequestBody defines body for PutYoutubeCookiesApiV1YoutubeCookiesPut for multipart/form-data ContentType.
type PutYoutubeCookiesApiV1YoutubeCookiesPutMultipartRequestBody = BodyPutYoutubeCookiesApiV1YoutubeCookiesPut

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HealthApiV1HealthGet request
	HealthApiV1HealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTaskApiV1TasksPostWithBody request with any body
	CreateTaskApiV1TasksPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteTaskApiV1TasksTaskIdDelete request
	DeleteTaskApiV1TasksTaskIdDelete(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTaskStatusApiV1TasksTaskIdGet request
	GetTaskStatusApiV1TasksTaskIdGet(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTaskResultApiV1TasksTaskIdResultGet request
	GetTaskResultApiV1TasksTaskIdResultGet(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTaskResultUrlApiV1TasksTaskIdResultUrlGet request
	GetTaskResultUrlApiV1TasksTaskIdResultUrlGet(ctx context.Context, taskId string, params *GetTaskResultUrlApiV1TasksTaskIdResultUrlGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTaskTranscriptApiV1TasksTaskIdTranscriptGet request
	GetTaskTranscriptApiV1TasksTaskIdTranscriptGet(ctx context.Context, taskId string, params *GetTaskTranscriptApiV1TasksTaskIdTranscriptGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUploadUrlApiV1UploadsPostWithBody request with any body
	CreateUploadUrlApiV1UploadsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUploadUrlApiV1UploadsPost(ctx context.Context, body CreateUploadUrlApiV1UploadsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteYoutubeCookiesApiV1YoutubeCookiesDelete request
	DeleteYoutubeCookiesApiV1YoutubeCookiesDelete(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetYoutubeCookiesApiV1YoutubeCookiesGet request
	GetYoutubeCookiesApiV1YoutubeCookiesGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutYoutubeCookiesApiV1YoutubeCookiesPutWithBody request with any body
	PutYoutubeCookiesApiV1YoutubeCookiesPutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HealthApiV1HealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthApiV1HealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTaskApiV1TasksPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTaskApiV1TasksPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteTaskApiV1TasksTaskIdDelete(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTaskApiV1TasksTaskIdDeleteRequest(c.Server, taskId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTaskStatusApiV1TasksTaskIdGet(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTaskStatusApiV1TasksTaskIdGetRequest(c.Server, taskId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTaskResultApiV1TasksTaskIdResultGet(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTaskResultApiV1TasksTaskIdResultGetRequest(c.Server, taskId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTaskResultUrlApiV1TasksTaskIdResultUrlGet(ctx context.Context, taskId string, params *GetTaskResultUrlApiV1TasksTaskIdResultUrlGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTaskResultUrlApiV1TasksTaskIdResultUrlGetRequest(c.Server, taskId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTaskTranscriptApiV1TasksTaskIdTranscriptGet(ctx context.Context, taskId string, params *GetTaskTranscriptApiV1TasksTaskIdTranscriptGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTaskTranscriptApiV1TasksTaskIdTranscriptGetRequest(c.Server, taskId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUploadUrlApiV1UploadsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadUrlApiV1UploadsPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUploadUrlApiV1UploadsPost(ctx context.Context, body CreateUploadUrlApiV1UploadsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadUrlApiV1UploadsPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteYoutubeCookiesApiV1YoutubeCookiesDelete(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteYoutubeCookiesApiV1YoutubeCookiesDeleteRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetYoutubeCookiesApiV1YoutubeCookiesGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetYoutubeCookiesApiV1YoutubeCookiesGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutYoutubeCookiesApiV1YoutubeCookiesPutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutYoutubeCookiesApiV1YoutubeCookiesPutRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthApiV1HealthGetRequest generates requests for HealthApiV1HealthGet
func NewHealthApiV1HealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateTaskApiV1TasksPostRequestWithBody generates requests for CreateTaskApiV1TasksPost with any type of body
func NewCreateTaskApiV1TasksPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteTaskApiV1TasksTaskIdDeleteRequest generates requests for DeleteTaskApiV1TasksTaskIdDelete
func NewDeleteTaskApiV1TasksTaskIdDeleteRequest(server string, taskId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "task_id", taskId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTaskStatusApiV1TasksTaskIdGetRequest generates requests for GetTaskStatusApiV1TasksTaskIdGet
func NewGetTaskStatusApiV1TasksTaskIdGetRequest(server string, taskId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "task_id", taskId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTaskResultApiV1TasksTaskIdResultGetRequest generates requests for GetTaskResultApiV1TasksTaskIdResultGet
func NewGetTaskResultApiV1TasksTaskIdResultGetRequest(server string, taskId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "task_id", taskId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks/%s/result", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTaskResultUrlApiV1TasksTaskIdResultUrlGetRequest generates requests for GetTaskResultUrlApiV1TasksTaskIdResultUrlGet
func NewGetTaskResultUrlApiV1TasksTaskIdResultUrlGetRequest(server string, taskId string, params *GetTaskResultUrlApiV1TasksTaskIdResultUrlGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "task_id", taskId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks/%s/result-url", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Filename != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filename", *params.Filename, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTaskTranscriptApiV1TasksTaskIdTranscriptGetRequest generates requests for GetTaskTranscriptApiV1TasksTaskIdTranscriptGet
func NewGetTaskTranscriptApiV1TasksTaskIdTranscriptGetRequest(server string, taskId string, params *GetTaskTranscriptApiV1TasksTaskIdTranscriptGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "task_id", taskId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks/%s/transcript", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUploadUrlApiV1UploadsPostRequest calls the generic CreateUploadUrlApiV1UploadsPost builder with application/json body
func NewCreateUploadUrlApiV1UploadsPostRequest(server string, body CreateUploadUrlApiV1UploadsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUploadUrlApiV1UploadsPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateUploadUrlApiV1UploadsPostRequestWithBody generates requests for CreateUploadUrlApiV1UploadsPost with any type of body
func NewCreateUploadUrlApiV1UploadsPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/uploads")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteYoutubeCookiesApiV1YoutubeCookiesDeleteRequest generates requests for DeleteYoutubeCookiesApiV1YoutubeCookiesDelete
func NewDeleteYoutubeCookiesApiV1YoutubeCookiesDeleteRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/youtube/cookies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetYoutubeCookiesApiV1YoutubeCookiesGetRequest generates requests for GetYoutubeCookiesApiV1YoutubeCookiesGet
func NewGetYoutubeCookiesApiV1YoutubeCookiesGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/youtube/cookies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutYoutubeCookiesApiV1YoutubeCookiesPutRequestWithBody generates requests for PutYoutubeCookiesApiV1YoutubeCookiesPut with any type of body
func NewPutYoutubeCookiesApiV1YoutubeCookiesPutRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/youtube/cookies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HealthApiV1HealthGetWithResponse request
	HealthApiV1HealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthApiV1HealthGetResponse, error)

	// CreateTaskApiV1TasksPostWithBodyWithResponse request with any body
	CreateTaskApiV1TasksPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTaskApiV1TasksPostResponse, error)

	// DeleteTaskApiV1TasksTaskIdDeleteWithResponse request
	DeleteTaskApiV1TasksTaskIdDeleteWithResponse(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*DeleteTaskApiV1TasksTaskIdDeleteResponse, error)

	// GetTaskStatusApiV1TasksTaskIdGetWithResponse request
	GetTaskStatusApiV1TasksTaskIdGetWithResponse(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*GetTaskStatusApiV1TasksTaskIdGetResponse, error)

	// GetTaskResultApiV1TasksTaskIdResultGetWithResponse request
	GetTaskResultApiV1TasksTaskIdResultGetWithResponse(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*GetTaskResultApiV1TasksTaskIdResultGetResponse, error)

	// GetTaskResultUrlApiV1TasksTaskIdResultUrlGetWithResponse request
	GetTaskResultUrlApiV1TasksTaskIdResultUrlGetWithResponse(ctx context.Context, taskId string, params *GetTaskResultUrlApiV1TasksTaskIdResultUrlGetParams, reqEditors ...RequestEditorFn) (*GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse, error)

	// GetTaskTranscriptApiV1TasksTaskIdTranscriptGetWithResponse request
	GetTaskTranscriptApiV1TasksTaskIdTranscriptGetWithResponse(ctx context.Context, taskId string, params *GetTaskTranscriptApiV1TasksTaskIdTranscriptGetParams, reqEditors ...RequestEditorFn) (*GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse, error)

	// CreateUploadUrlApiV1UploadsPostWithBodyWithResponse request with any body
	CreateUploadUrlApiV1UploadsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadUrlApiV1UploadsPostResponse, error)

	CreateUploadUrlApiV1UploadsPostWithResponse(ctx context.Context, body CreateUploadUrlApiV1UploadsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadUrlApiV1UploadsPostResponse, error)

	// DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteWithResponse request
	DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse, error)

	// GetYoutubeCookiesApiV1YoutubeCookiesGetWithResponse request
	GetYoutubeCookiesApiV1YoutubeCookiesGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetYoutubeCookiesApiV1YoutubeCookiesGetResponse, error)

	// PutYoutubeCookiesApiV1YoutubeCookiesPutWithBodyWithResponse request with any body
	PutYoutubeCookiesApiV1YoutubeCookiesPutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutYoutubeCookiesApiV1YoutubeCookiesPutResponse, error)
}

type HealthApiV1HealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
}

// Status returns HTTPResponse.Status
func (r HealthApiV1HealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthApiV1HealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthApiV1HealthGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateTaskApiV1TasksPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateTaskResponse
	JSON400      *ErrorResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateTaskApiV1TasksPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTaskApiV1TasksPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateTaskApiV1TasksPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteTaskApiV1TasksTaskIdDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r DeleteTaskApiV1TasksTaskIdDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteTaskApiV1TasksTaskIdDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteTaskApiV1TasksTaskIdDeleteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTaskStatusApiV1TasksTaskIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TaskStatusResponse
	JSON404      *ErrorResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetTaskStatusApiV1TasksTaskIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTaskStatusApiV1TasksTaskIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTaskStatusApiV1TasksTaskIdGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTaskResultApiV1TasksTaskIdResultGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON404      *ErrorResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetTaskResultApiV1TasksTaskIdResultGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTaskResultApiV1TasksTaskIdResultGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTaskResultApiV1TasksTaskIdResultGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResultUrlResponse
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON400      *TranscriptInvalidFormatError
	JSON404      *TranscriptNotFoundError
	JSON409      *TranscriptFailedError
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateUploadUrlApiV1UploadsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UploadUrlResponse
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateUploadUrlApiV1UploadsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUploadUrlApiV1UploadsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateUploadUrlApiV1UploadsPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetYoutubeCookiesApiV1YoutubeCookiesGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CookieStatusResponse
}

// Status returns HTTPResponse.Status
func (r GetYoutubeCookiesApiV1YoutubeCookiesGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetYoutubeCookiesApiV1YoutubeCookiesGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetYoutubeCookiesApiV1YoutubeCookiesGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutYoutubeCookiesApiV1YoutubeCookiesPutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CookieStatusResponse
	JSON400      *ErrorResponse
	JSON413      *ErrorResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r PutYoutubeCookiesApiV1YoutubeCookiesPutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutYoutubeCookiesApiV1YoutubeCookiesPutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutYoutubeCookiesApiV1YoutubeCookiesPutResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// HealthApiV1HealthGetWithResponse request returning *HealthApiV1HealthGetResponse
func (c *ClientWithResponses) HealthApiV1HealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthApiV1HealthGetResponse, error) {
	rsp, err := c.HealthApiV1HealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthApiV1HealthGetResponse(rsp)
}

// CreateTaskApiV1TasksPostWithBodyWithResponse request with arbitrary body returning *CreateTaskApiV1TasksPostResponse
func (c *ClientWithResponses) CreateTaskApiV1TasksPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTaskApiV1TasksPostResponse, error) {
	rsp, err := c.CreateTaskApiV1TasksPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTaskApiV1TasksPostResponse(rsp)
}

// DeleteTaskApiV1TasksTaskIdDeleteWithResponse request returning *DeleteTaskApiV1TasksTaskIdDeleteResponse
func (c *ClientWithResponses) DeleteTaskApiV1TasksTaskIdDeleteWithResponse(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*DeleteTaskApiV1TasksTaskIdDeleteResponse, error) {
	rsp, err := c.DeleteTaskApiV1TasksTaskIdDelete(ctx, taskId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTaskApiV1TasksTaskIdDeleteResponse(rsp)
}

// GetTaskStatusApiV1TasksTaskIdGetWithResponse request returning *GetTaskStatusApiV1TasksTaskIdGetResponse
func (c *ClientWithResponses) GetTaskStatusApiV1TasksTaskIdGetWithResponse(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*GetTaskStatusApiV1TasksTaskIdGetResponse, error) {
	rsp, err := c.GetTaskStatusApiV1TasksTaskIdGet(ctx, taskId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTaskStatusApiV1TasksTaskIdGetResponse(rsp)
}

// GetTaskResultApiV1TasksTaskIdResultGetWithResponse request returning *GetTaskResultApiV1TasksTaskIdResultGetResponse
func (c *ClientWithResponses) GetTaskResultApiV1TasksTaskIdResultGetWithResponse(ctx context.Context, taskId string, reqEditors ...RequestEditorFn) (*GetTaskResultApiV1TasksTaskIdResultGetResponse, error) {
	rsp, err := c.GetTaskResultApiV1TasksTaskIdResultGet(ctx, taskId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTaskResultApiV1TasksTaskIdResultGetResponse(rsp)
}

// GetTaskResultUrlApiV1TasksTaskIdResultUrlGetWithResponse request returning *GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse
func (c *ClientWithResponses) GetTaskResultUrlApiV1TasksTaskIdResultUrlGetWithResponse(ctx context.Context, taskId string, params *GetTaskResultUrlApiV1TasksTaskIdResultUrlGetParams, reqEditors ...RequestEditorFn) (*GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse, error) {
	rsp, err := c.GetTaskResultUrlApiV1TasksTaskIdResultUrlGet(ctx, taskId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse(rsp)
}

// GetTaskTranscriptApiV1TasksTaskIdTranscriptGetWithResponse request returning *GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse
func (c *ClientWithResponses) GetTaskTranscriptApiV1TasksTaskIdTranscriptGetWithResponse(ctx context.Context, taskId string, params *GetTaskTranscriptApiV1TasksTaskIdTranscriptGetParams, reqEditors ...RequestEditorFn) (*GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse, error) {
	rsp, err := c.GetTaskTranscriptApiV1TasksTaskIdTranscriptGet(ctx, taskId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse(rsp)
}

// CreateUploadUrlApiV1UploadsPostWithBodyWithResponse request with arbitrary body returning *CreateUploadUrlApiV1UploadsPostResponse
func (c *ClientWithResponses) CreateUploadUrlApiV1UploadsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadUrlApiV1UploadsPostResponse, error) {
	rsp, err := c.CreateUploadUrlApiV1UploadsPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadUrlApiV1UploadsPostResponse(rsp)
}

func (c *ClientWithResponses) CreateUploadUrlApiV1UploadsPostWithResponse(ctx context.Context, body CreateUploadUrlApiV1UploadsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadUrlApiV1UploadsPostResponse, error) {
	rsp, err := c.CreateUploadUrlApiV1UploadsPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadUrlApiV1UploadsPostResponse(rsp)
}

// DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteWithResponse request returning *DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse
func (c *ClientWithResponses) DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse, error) {
	rsp, err := c.DeleteYoutubeCookiesApiV1YoutubeCookiesDelete(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse(rsp)
}

// GetYoutubeCookiesApiV1YoutubeCookiesGetWithResponse request returning *GetYoutubeCookiesApiV1YoutubeCookiesGetResponse
func (c *ClientWithResponses) GetYoutubeCookiesApiV1YoutubeCookiesGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetYoutubeCookiesApiV1YoutubeCookiesGetResponse, error) {
	rsp, err := c.GetYoutubeCookiesApiV1YoutubeCookiesGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetYoutubeCookiesApiV1YoutubeCookiesGetResponse(rsp)
}

// PutYoutubeCookiesApiV1YoutubeCookiesPutWithBodyWithResponse request with arbitrary body returning *PutYoutubeCookiesApiV1YoutubeCookiesPutResponse
func (c *ClientWithResponses) PutYoutubeCookiesApiV1YoutubeCookiesPutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutYoutubeCookiesApiV1YoutubeCookiesPutResponse, error) {
	rsp, err := c.PutYoutubeCookiesApiV1YoutubeCookiesPutWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutYoutubeCookiesApiV1YoutubeCookiesPutResponse(rsp)
}

// ParseHealthApiV1HealthGetResponse parses an HTTP response from a HealthApiV1HealthGetWithResponse call
func ParseHealthApiV1HealthGetResponse(rsp *http.Response) (*HealthApiV1HealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthApiV1HealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateTaskApiV1TasksPostResponse parses an HTTP response from a CreateTaskApiV1TasksPostWithResponse call
func ParseCreateTaskApiV1TasksPostResponse(rsp *http.Response) (*CreateTaskApiV1TasksPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTaskApiV1TasksPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateTaskResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseDeleteTaskApiV1TasksTaskIdDeleteResponse parses an HTTP response from a DeleteTaskApiV1TasksTaskIdDeleteWithResponse call
func ParseDeleteTaskApiV1TasksTaskIdDeleteResponse(rsp *http.Response) (*DeleteTaskApiV1TasksTaskIdDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteTaskApiV1TasksTaskIdDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetTaskStatusApiV1TasksTaskIdGetResponse parses an HTTP response from a GetTaskStatusApiV1TasksTaskIdGetWithResponse call
func ParseGetTaskStatusApiV1TasksTaskIdGetResponse(rsp *http.Response) (*GetTaskStatusApiV1TasksTaskIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTaskStatusApiV1TasksTaskIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TaskStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetTaskResultApiV1TasksTaskIdResultGetResponse parses an HTTP response from a GetTaskResultApiV1TasksTaskIdResultGetWithResponse call
func ParseGetTaskResultApiV1TasksTaskIdResultGetResponse(rsp *http.Response) (*GetTaskResultApiV1TasksTaskIdResultGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTaskResultApiV1TasksTaskIdResultGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/zip) unsupported

	}

	return response, nil
}

// ParseGetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse parses an HTTP response from a GetTaskResultUrlApiV1TasksTaskIdResultUrlGetWithResponse call
func ParseGetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse(rsp *http.Response) (*GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTaskResultUrlApiV1TasksTaskIdResultUrlGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResultUrlResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse parses an HTTP response from a GetTaskTranscriptApiV1TasksTaskIdTranscriptGetWithResponse call
func ParseGetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse(rsp *http.Response) (*GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTaskTranscriptApiV1TasksTaskIdTranscriptGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest TranscriptInvalidFormatError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest TranscriptNotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest TranscriptFailedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParseCreateUploadUrlApiV1UploadsPostResponse parses an HTTP response from a CreateUploadUrlApiV1UploadsPostWithResponse call
func ParseCreateUploadUrlApiV1UploadsPostResponse(rsp *http.Response) (*CreateUploadUrlApiV1UploadsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUploadUrlApiV1UploadsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UploadUrlResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseDeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse parses an HTTP response from a DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteWithResponse call
func ParseDeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse(rsp *http.Response) (*DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteYoutubeCookiesApiV1YoutubeCookiesDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetYoutubeCookiesApiV1YoutubeCookiesGetResponse parses an HTTP response from a GetYoutubeCookiesApiV1YoutubeCookiesGetWithResponse call
func ParseGetYoutubeCookiesApiV1YoutubeCookiesGetResponse(rsp *http.Response) (*GetYoutubeCookiesApiV1YoutubeCookiesGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetYoutubeCookiesApiV1YoutubeCookiesGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CookieStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutYoutubeCookiesApiV1YoutubeCookiesPutResponse parses an HTTP response from a PutYoutubeCookiesApiV1YoutubeCookiesPutWithResponse call
func ParsePutYoutubeCookiesApiV1YoutubeCookiesPutResponse(rsp *http.Response) (*PutYoutubeCookiesApiV1YoutubeCookiesPutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutYoutubeCookiesApiV1YoutubeCookiesPutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CookieStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
